name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main  # Or your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        run: |
          cd backend/quiz  # Navigate to the correct folder where pom.xml is located
          mvn clean install -DskipTests=false  # Run tests during build
          
      - name: Upload test results (optional)
        if: failure()
        run: |
          mkdir -p $GITHUB_WORKSPACE/test-results
          cp backend/quiz/target/surefire-reports/* $GITHUB_WORKSPACE/test-results
        continue-on-error: true
