name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main  # Or your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build and test with Maven
        run: |
          cd backend/quiz  
          mvn clean install -X
        
